basics1/basics1/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/',user_views.register, name='register'),
    path('login/', user_views.user_login,name='login'),
    path('logout/', user_views.user_logout,name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
] 

urlpatterns += [

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basics1/food/urls.py
from django.urls import path
from . import views


app_name = 'food'
urlpatterns = [
    path('', views.IndexClassView.as_view(), name='home'),
    path('item/', views.item, name='item'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('add', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:id>/', views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
]

basics1/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

basics1/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username
    

basics1/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

basics1/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

basics1/food/views.py
from django.forms import BaseModelForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.

def home(request):
    item_list = Item.objects.all()
    template = loader.get_template('food/index.html')
    context = {
        'item_list':item_list,
    }
    return render(request, 'food/index.html',context)


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse('<h1>This is an item</h1>')

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request, 'food/detail.html',context);

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'
    

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:home')
    
    return render(request,'food/item-form.html',{'form':form})

class CreateItem(CreateView):
    model         = Item
    fields        = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)

def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:home')
    
    return render(request, 'food/item-form.html',{'form':form,'item':item})

def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:home')
    
    return render(request, 'food/item-delete.html',{'item':item})

basics1/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm, LoginForm
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome { username }, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    
    return render(request, 'users/register.html',{'form':form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('http://127.0.0.1:8000/food/')
    else:
        form = LoginForm()

    return render(request, 'users/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return render(request, 'users/logout.html', {})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

basics1/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>
        
        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item nav-link" href="#">Delete Item</a>
            <a class="nav-item nav-link" href="#">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tag }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

basics1/templates/food/detail.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="{{ item.item_image }}" class="card"/>
                </div>
                <div class="col-md-6">
                    <h1>{{ object.item_name }}</h1>
                    <h2>{{ object.item_desc }}</h2>
                    <h3>${{ object.item_price }}</h3>
                    <a href="{% url 'food:delete_item' item.id %}">Delete</a>
                </div>
            </div>
        </div>
    {% endblock %}
</body>
</html>

basics1/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
        <ul>
            {% for item in item_list%}
                <div class="row">
                    <div class="col-md-3 offset-md-2">
                        <img class="card" height="150px" src="{{ item.item_image }}"/>
                    </div>
                    <div class="col-md-4">
                        <h3>{{ item.item_name }}</h3>
                        <h4>{{ item.item_desc }}</h4>
                        <h5>${{ item.item_price }}</h5>
                        <h6>{{ item.user_name }}</h6>
                    </div>
                    <div class="col-md-2">
                        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
                    </div>
                </div>
            {% endfor %}
        </ul>
    {% endblock %}
</body>
</html>

basics1/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        <h2>Are you sure that you want to delete {{ item.item_name }}</h2>
        <button type="submit">Confirm</button>
    </form>
{% endblock %}

basics1/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Add new item
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <br>
                            <button class="text-white btn-info" type="submit">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

basics1/templates/index.html
<p>Hello man!</p>

basics1/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn-info text-white" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

basics1/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>You have been logged out</h1>    
</body>
</html>

basics1/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ user.username }}</h1>
    <img src="{{ user.profile.image.url }}">
</body>
</html>

basics1/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <br>
                            <button class="text-white btn-info" type="submit">Sign Up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}